inputs:
  name:
    description: 'Action name'
    default: 'Train and test the model'
  gcp_service_key:
    description: 'GCP key'
    default: ''
runs:
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: livepeer-ml
        service_account_key: ${{ inputs.gcp_service_key }}
        export_default_credentials: true
    - name: Install global dependencies
      shell: bash
      run: python3 -m pip install -r requirements.txt
#    - name: Install model dependencies
#      run: if [ -f content-classification/requirements.txt ]; then python3 -m pip install -r content-classification/requirements.txt; fi
#    - name: Sync the dataset
#      run: gsutil -m rsync -i -d -r gs://livepeer-ml-data /ccl-data/data
#    - name: Create data splits
#      run: |
#        cd utils
#        python3 split.py --data_dir /ccl-data/data/ --splits_out_dir /ccl-data/splits/ --out_dir /ccl-data/splits/ --resize_to 224,224
#    - name: Train model
#      run: |
#        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
#        cd $GITHUB_WORKSPACE/content-classification/scripts/
#        python3 train.py --data_dir /ccl-data/splits/ --num_epochs 2 --batch_size 256
#    - name: Test model
#      run: |
#        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
#        cd $GITHUB_WORKSPACE/content-classification/scripts/
#        python3 test.py --data_dir /ccl-data/splits/
